<h3>3 steps to using SmugImport</h3>
<ul class="help-box">
    <li>
        <div class="roundedcornr_box_867993">
            <div class="roundedcornr_top_867993"><div></div></div>
            <div class="roundedcornr_content_867993">
                <img src="<?php echo $this->baseUrl() . '/assets/images/Settings.png' ?>" />
                <h3>Step 1</h3>
                <p>On the <a href="settings">Settings tab</a>, enter your SmugMug nickname.</p>
            </div>
            <div class="roundedcornr_bottom_867993"><div></div></div>
        </div>
    </li>
    <li>
        <div class="roundedcornr_box_867993">
            <div class="roundedcornr_top_867993"><div></div></div>
            <div class="roundedcornr_content_867993">
                <img src="<?php echo $this->baseUrl() . '/assets/images/Pictures.png' ?>" />
                <h3>Step 2</h3>
                <p>On the <a href="import">Import tab</a>, select the SmugMug album you want to import from and the Facebook album you want to import to.<br />
                    (Only public SmugMug albums are supported at present.)</p>
            </div>
            <div class="roundedcornr_bottom_867993"><div></div></div>
        </div>
    </li>
    <li>
        <div class="roundedcornr_box_867993">
            <div class="roundedcornr_top_867993"><div></div></div>
            <div class="roundedcornr_content_867993">
                <img src="<?php echo $this->baseUrl() . '/assets/images/Select.png' ?>" />
                <h3>Step 3</h3>
                <p>Click Import!</p>
            </div>
            <div class="roundedcornr_bottom_867993"><div></div></div>
        </div>
    </li>
</ul>

<h3>FAQ</h3>
<dl class="faq">
    <dt>Why don't my photos appear in my Facebook album after import?</dt>
    <dd>Newly imported photos will be in a 'pending' state. You need to approve them beore they appear in your Facebook album.</dd>
    <dt>Why isn't my new SmugMug album showing up?</dt>
    <dd>The album list is cached for 5 minutes. To force a reload <a href="import/form/reload/1">click here.</a></dd>
    <dt>How can I check if SmugMug is down for maintenance?</dt>
    <dd>SmugMug perform periodic maintenance which can disable access via the API.<br >
        SmugImport uses the SmugMug API, so when the API is down so is SmugImport. Check the <a href="http://smugmug.wordpress.com" target="_blank">SmugMug status blog</a> to see if they are performing maintenance.</dd>
</dl>

<div class="fbgreybox">
    <h3>Want to save $5 on a SmugMug subscription?</h3>
    <p>It's simple. Just click on <a target="_blank" href="http://www.smugmug.com/?referrer=nSI666N7VfmEN">this referral link</a> or use the following coupon in the <em>Referred by</em> field on the <a target="_blank" href="https://secure.smugmug.com/signup.mg">SmugMug signup form</a>:<br />
    <center><strong>nSI666N7VfmEN</strong></center></p>
</div>


